/**
 * R4 — platform format limits (spec section 3, severity: error).
 *
 * Every number here comes from `context.platformLimits`, which
 * socialLint.js loads straight from S1's data/platformLimits.json — this
 * file never repeats a limit value itself (spec: "값을 다시 적지 않고 그
 * 파일을 참조한다"). X's post uses S1's own effectiveXLength() so the
 * 23-char URL rule is computed identically to how S1 enforced it at
 * generation time.
 */

import { effectiveXLength } from '../../generate/socialPost.js';
import { buildExcerpt } from '../similarity.js';

export function check(textpack, context) {
  const { platformLimits } = context;
  const violations = [];
  let checkedCount = 0;

  const evaluate = (path, length, limit, unit, excerptSource) => {
    checkedCount += 1;
    if (limit === undefined || limit === null) return;
    if (length > limit) {
      violations.push({
        rule: 'R4-platformRules',
        severity: 'error',
        path,
        message: `${path}이(가) ${unit === 'chars' ? '글자수' : '개수'} 제한을 초과했습니다: ${length}/${limit}`,
        value: length,
        threshold: limit,
        comparedWith: { source: 'data/platformLimits.json' },
        excerpt: excerptSource ? buildExcerpt(excerptSource) : `${length}${unit === 'chars' ? '자' : '개'}`,
      });
    }
  };

  if (textpack.youtube) {
    (textpack.youtube.titles || []).forEach((t, i) => evaluate(`youtube.titles.${i}`, t.length, platformLimits.youtube?.titleMax, 'chars', t));
    if (textpack.youtube.description) evaluate('youtube.description', textpack.youtube.description.length, platformLimits.youtube?.descMax, 'chars', textpack.youtube.description);
    if (Array.isArray(textpack.youtube.hashtags)) evaluate('youtube.hashtags', textpack.youtube.hashtags.length, platformLimits.youtube?.hashtagCount, 'count');
    if (Array.isArray(textpack.youtube.tags)) evaluate('youtube.tags', textpack.youtube.tags.join(', ').length, platformLimits.youtube?.tagsTotalMax, 'chars');
  }

  if (textpack.instagram) {
    if (textpack.instagram.caption) evaluate('instagram.caption', textpack.instagram.caption.length, platformLimits.instagram?.captionMax, 'chars', textpack.instagram.caption);
    if (Array.isArray(textpack.instagram.hashtags)) evaluate('instagram.hashtags', textpack.instagram.hashtags.length, platformLimits.instagram?.hashtagMax, 'count');
  }

  if (textpack.x?.main) {
    const length = effectiveXLength(textpack.x.main, platformLimits.x?.urlLength ?? 23);
    evaluate('x.main', length, platformLimits.x?.postMax, 'chars', textpack.x.main);
  }

  if (textpack.facebook?.body) {
    evaluate('facebook.body', textpack.facebook.body.length, platformLimits.facebook?.postMax, 'chars', textpack.facebook.body);
  }

  if (Array.isArray(textpack.naver?.tags)) {
    evaluate('naver.tags', textpack.naver.tags.length, platformLimits.naver?.tagMax, 'count');
  }

  // Not generated by S1 yet, but checked defensively per spec section 3 R4
  // ("Threads 항목이 있으면 해시태그 1개 초과 시 위반") in case it ever is.
  if (Array.isArray(textpack.threads?.hashtags)) {
    evaluate('threads.hashtags', textpack.threads.hashtags.length, platformLimits.threads?.hashtagMax, 'count');
  }

  return { violations, checkedCount: Math.max(checkedCount, 1) };
}
